### ISSUE TITLE
Issues with Higher Resolution Source & Target

### ISSUE THREAD

**Issue by pidginred** [AliaksandrSiarohin/motion-cosegmentation#5]
@AliaksandrSiarohin Following up on https://github.com/AliaksandrSiarohin/first-order-model/issues/20, getting an error trying to run this with 512x512 source & target. Here are my configs & the full errors.

## Diff

```diff
diff --git a/config/vox-256-sem-10segments.yaml b/config/vox-256-sem-10segments.yaml
index 5871c97..eda5d74 100644
--- a/config/vox-256-sem-10segments.yaml
+++ b/config/vox-256-sem-10segments.yaml
@@ -39,7 +39,7 @@ model_params:
      num_blocks: 5
      # Segmentations is predicted on smaller images for better performance,
      # scale_factor=0.25 means that 256x256 image will be resized to 64x64
-     scale_factor: 0.25
+     scale_factor: 0.125
   reconstruction_module_params:
     # Number of features mutliplier
     block_expansion: 64
diff --git a/modules/util.py b/modules/util.py
index 7530acd..cccab51 100644
--- a/modules/util.py
+++ b/modules/util.py
@@ -198,7 +198,7 @@ class Hourglass(nn.Module):
 class AntiAliasInterpolation2d(nn.Module):
     def __init__(self, channels, scale):
         super(AntiAliasInterpolation2d, self).__init__()
-        sigma = (1 / scale - 1) / 2
+        sigma = 1.5 # Hard coded as per issues/20#issuecomment-600784060
         kernel_size = 2 * round(sigma * 4) + 1
         self.ka = kernel_size // 2
         self.kb = self.ka - 1 if kernel_size % 2 == 0 else self.ka
diff --git a/part_swap.py b/part_swap.py
index 2d8aad0..4d185d6 100644
--- a/part_swap.py
+++ b/part_swap.py
@@ -222,8 +222,8 @@ if __name__ == "__main__":
     source_image = imageio.imread(opt.source_image)
 
     target_video = imageio.mimread(opt.target_video, memtest=False)
-    source_image = resize(source_image, (256, 256))[..., :3]
-    target_video = [resize(frame, (256, 256))[..., :3] for frame in target_video]
+    source_image = resize(source_image, (512, 512))[..., :3]
+    target_video = [resize(frame, (512, 512))[..., :3] for frame in target_video]
 
     blend_scale = (256 / 4) / 512 if opt.supervised else 1
     reconstruction_module, segmentation_module = load_checkpoints(opt.config, opt.checkpoint, blend_scale=blend_scale, 
```

## Errors

```
(base) C:\Users\admin\git\motion-cosegmentation>python part_swap.py --config config/vox-256-sem-10segments.yaml --result_video 0123456789_result.mp4 --target_video target_512_long.mp4 --source_image source.jpg --checkpoint "C:\Users\admin\Downloads\vox-10segments.pth.tar" --swap_index 0,1,2,3,4,5,6,7,8,9
C:\Users\admin\Anaconda3\lib\site-packages\skimage\transform\_warps.py:105: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
C:\Users\admin\Anaconda3\lib\site-packages\skimage\transform\_warps.py:110: UserWarning: Anti-aliasing will be enabled by default in skimage 0.15 to avoid aliasing artifacts when down-sampling images.
  warn("Anti-aliasing will be enabled by default in skimage 0.15 to "
part_swap.py:105: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
  0%|                                                                          | 0/449 [00:00<?, ?it/s]C:\Users\admin\Anaconda3\lib\site-packages\torch\nn\functional.py:2423: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))

Traceback (most recent call last):
  File "part_swap.py", line 237, in <module>
    face_parser, hard=opt.hard, use_source_segmentation=opt.use_source_segmentation, cpu=opt.cpu)
  File "part_swap.py", line 194, in make_video
    blend_mask=blend_mask, use_source_segmentation=use_source_segmentation)
  File "C:\Users\admin\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\admin\Anaconda3\lib\site-packages\torch\nn\parallel\data_parallel.py", line 141, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "C:\Users\admin\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "part_swap.py", line 88, in forward
    out = enc_target * (1 - blend_mask) + enc_source * blend_mask
RuntimeError: The size of tensor a (128) must match the size of tensor b (64) at non-singleton dimension 3
```

**Comment by AliaksandrSiarohin** [comment]
You should change the scale of bleeding mask. E.g blend_scale=0.5

**Comment by pidginred** [comment]
@AliaksandrSiarohin Confirmed that works. Thank you.

**Comment by konstiantyn** [comment]
![Untitled](https://user-images.githubusercontent.com/33037366/104152820-0424ab80-5424-11eb-8a44-d9162636e0d5.jpg)
How can I resize blending mask to 128*128?
